apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-master
spec:
  replicas: 1
  selector:
    app: jenkins-master
  template:
    metadata:
      name: jenkins-master
      labels:
        app: jenkins-master
    spec:
      volumes:
      - name: shared-ai-agent
        emptyDir: {}
      imagePullSecrets:
        - name: myregistrykey
      initContainers:
      - name: ai-init-container
        image: gelabsregistry.azurecr.io/ai-init-container:latest
        volumeMounts:
        - name: shared-ai-agent
          mountPath: /shared-ai-agent/   
      containers:
      - name: jenkins-master
        image: jenkins/jenkins:latest
        ports:
        - containerPort: 8080
        env:
        - name: APPLICATION_INSIGHTS_IKEY
          value: "[APP INSIGHTS IKEY]"
        - name: JAVA_TOOL_OPTIONS
          value: "-Djenkins.model.Jenkins.crumbIssuerProxyCompatibility=true -javaagent:/shared-ai-agent/applicationinsights-agent.jar -DapplicationInsights.configurationFile=/shared-ai-agent/ApplicationInsights.json"
        volumeMounts:
        - name: shared-ai-agent
          mountPath: /shared-ai-agent/
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: jenkins-master